name: Echo
on:
  push:


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: echo
      run: |
        echo "::add-mask::$RELEASE_VERSION"
        echo RELEASE_VERSION
