name: Echo
on:
  push:


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: RELEASE_VERSION=${GITHUB_REF#refs/*/}
    - name: echo
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
