name: Echo
on:
  push:


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: echo
      run: |
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        echo "::add-mask::$RELEASE_VERSION"
        echo $RELEASE_VERSION
        echo "::set-output name=NEXT_STEP::$RELEASE_VERSION"
      id: hoge
    - name: echo next
      run: 
