name: Deploy-Staging-Production

on:
  workflow_dispatch:

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - run: echo deploy staging
      - run: echo secret ${{ secrets.SAMPLE_SECRET }}
  
  deploy_production:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - run: echo deploy production
      - run: echo secret ${{ secrets.SAMPLE_SECRET }}