name: Deploy-Staging-Production

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

run-name: Deploy ${ github.event.inputs.environment } 

jobs:
  deploy_staging:
    if: github.event.inputs.environment == 'staging'
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://yahoo.co.jp
    steps:
      - run: echo "this is ${{github.event.inputs.environment}}"
      - run: echo "this is ${{github.event.inputs.environment}}"
      - run: echo deploy staging
      - run: echo secret ${{ secrets.SAMPLE_SECRET }}
  
  deploy_production:
    if: github.event.inputs.environment == 'production'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://google.com
    steps:
      - run: echo deploy production
      - run: echo secret ${{ secrets.SAMPLE_SECRET }}