name: Go test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ububuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: go build -v ./...
      - name: Te!Split 