name: set-output-test

on:
  push:

jobs:
  echosetoutput:
    steps:
      - id: test_id
        name: test_name
        run: echo "::set-output name=test::hoge"

      - run: echo "${{ steps.test_id.outputs.test }}"